Collapse static handler tests
dogmatiq/configkit pull request #137
Opened 2021-03-20 07:31 UTC by danilvpetrov

#### What change does this introduce?

This PR collapses all static analysis handler tests into a single folder  `static/testdata/handlers`.

#### Why make this change?

This change is required to group the handler tests and reduce the number of test data and duration of the tests.

#### Is there anything you are unsure about?

No

#### What issues does this relate to?

Relates to https://github.com/dogmatiq/configkit/issues/104.

2021-03-21 03:42 UTC, jmalloc requested changes
Just some test descriptions need to be fixed up... otherwise great, much smaller!

2021-03-21 03:42 UTC, jmalloc commented on static/handler_test.go
> +	When("the application contains a single handler handler of a kind", func() {
```suggestion
	When("the application contains a single handler of each type", func() {
```

2021-03-21 03:42 UTC, jmalloc commented on static/handler_test.go
> +		It("returns the a single configuration for each handle kind", func() {
```suggestion
		It("returns a single configuration for each handler type", func() {
```

2021-03-21 03:42 UTC, jmalloc commented on static/handler_test.go
> +		It("returns all of the aggregate handler configurations", func() {
```suggestion
	When("the application multiple handlers of each type", func() {
		It("returns all of the handler configurations", func() {
```

2021-03-21 03:42 UTC, jmalloc commented on static/handler_test.go
> +	When("a nil value is passed as an aggregate handler", func() {
```suggestion
	When("a nil value is passed as a handler", func() {
```

2021-03-21 03:42 UTC, jmalloc commented on static/handler_test.go
> +		It("does not add an aggregate handler to the application configuration", func() {
```suggestion
		It("does not add a handler to the application configuration", func() {
```

2021-03-21 03:42 UTC, jmalloc commented on static/handler_test.go
> +		It("does not add the message to the aggregate configuration", func() {
```suggestion
		It("does not add the message to the handler configuration", func() {
```

2021-03-22 09:02 UTC, danilvpetrov commented
Ok, that's done, please let me know if there is anything else left to fix.

2021-03-22 21:35 UTC, jmalloc commented
Nah man, that's it.. merge away!

2021-03-23 00:39 UTC, merged